### ISSUE TITLE
Publishing Ribbon and Collab Master Page

### ISSUE THREAD

**Issue by StfBauer** [rdrisgill/sharepoint-starter-masterpages#1]
Hi Randy,
since SharePoint Foundation doesn't exist anymore you can use the publishing ribbon control on the colloab pages too.
Another thing I notice is that you have to wrap the publishing ribbon in a AjaxDelta control. Otherwise it will generate error in the event log.

/Stefan

**Comment by rdrisgill** [comment]
Both great comments. I hadn't thought of that first one but I guess that's right!

**Comment by johnfabian** [comment]
Are these all the controls that have to be on the page? I want a completely blank masterpage with only the ribbon controls on the page. I need to completely brand the portal so it doesn't look like SharePoint at all and also want to use bootstrap and all custom spfx controls and no out of the box controls. Is this possible?  Do i just need to wrap all the controls in a div with display="none" or can I just delete them from the page?
