### ISSUE TITLE
Master Question

### ISSUE THREAD

**Issue by johnfabian** [rdrisgill/sharepoint-starter-masterpages#2]
Are these all the controls that have to be on the page? I want a completely blank masterpage with only the ribbon controls on the page. I need to completely brand the portal so it doesn't look like SharePoint at all and also want to use bootstrap and all custom spfx controls and no out of the box controls. Is this possible? Do i just need to wrap all the controls in a div with display="none" or can I just delete them from the page?

**Comment by rdrisgill** [comment]
Think of the master page as the shell of a SP site and all the placeholders are required or SP will break. You can hide the ones you don’t want to show. 

 

That being said if you don’t want to show ANY of the default controls you might be better suited making your own UI and using client code to bring in SP content? That would be outside of the scope of the starter master pages.

 

What would probably be ideal for you is the concept of “Full Page SPFx Apps” which is planned by Microsoft but not a reality yet: https://www.voitanos.io/blog/what-s-next-for-the-sharepoint-framework

**Comment by johnfabian** [comment]
@rdrisgill I already do have a full page custom ui using angular and the rest api hosted in a document library for certain apps, I have custom web parts build with spfx but I wanted to be able to use some of  the content place holders that are wrapped with bootstrap since my spfx parts is bootstrap but was wondering which controls are required.

I do understand the content place holders need to be on the page but is it ok to remove the delegate controls? I do have a working example that has the ribbon but mostly set things to display: none but just wanted to clean up the markup to the bare min that won't break but not sure what problems I'll have removing delegate controls?  Mostly like the aspnet menu contol and the suitebar control and few others that I think would increase performance if they aren't on the page.

**Comment by rdrisgill** [comment]
Don’t forget you can set visible=false on placeholders and they won’t render their markup in HTML. As for whether you are good without the delegate, it depends on the delegate and also the page context. Sometimes they behave differently on different types of pages or sites. Mostly some kind of functionality won’t happen once your remove them.

**Comment by johnfabian** [comment]
@rdrisgill ok, thanks so much for the tips.
